/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PersonalTrainingRouteImport } from './routes/personal-training'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as SkillsIndexRouteImport } from './routes/skills.index'
import { Route as AuthenticatedLessonLessonIdRouteImport } from './routes/_authenticated/lesson.$lessonId'
import { Route as AuthenticatedOnboardingGoalsRouteImport } from './routes/_authenticated/onboarding.goals'
import { Route as AuthenticatedOnboardingLevelRouteImport } from './routes/_authenticated/onboarding.level'
import { Route as AuthenticatedOnboardingSkillsRouteImport } from './routes/_authenticated/onboarding.skills'
import { Route as SkillsSkillIdIndexRouteImport } from './routes/skills.$skillId.index'
import { Route as SkillsSkillIdPathwayRouteImport } from './routes/skills.$skillId.pathway'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalTrainingRoute = PersonalTrainingRouteImport.update({
  id: '/personal-training',
  path: '/personal-training',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLessonLessonIdRoute =
  AuthenticatedLessonLessonIdRouteImport.update({
    id: '/lesson/$lessonId',
    path: '/lesson/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingGoalsRoute =
  AuthenticatedOnboardingGoalsRouteImport.update({
    id: '/onboarding/goals',
    path: '/onboarding/goals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingLevelRoute =
  AuthenticatedOnboardingLevelRouteImport.update({
    id: '/onboarding/level',
    path: '/onboarding/level',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingSkillsRoute =
  AuthenticatedOnboardingSkillsRouteImport.update({
    id: '/onboarding/skills',
    path: '/onboarding/skills',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const SkillsSkillIdIndexRoute = SkillsSkillIdIndexRouteImport.update({
  id: '/skills/$skillId/',
  path: '/skills/$skillId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSkillIdPathwayRoute = SkillsSkillIdPathwayRouteImport.update({
  id: '/skills/$skillId/pathway',
  path: '/skills/$skillId/pathway',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/personal-training': typeof PersonalTrainingRoute
  '/signup': typeof SignupRoute
  '/subscription': typeof SubscriptionRoute
  '/welcome': typeof WelcomeRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skills/': typeof SkillsIndexRoute
  '/lesson/$lessonId': typeof AuthenticatedLessonLessonIdRoute
  '/onboarding/goals': typeof AuthenticatedOnboardingGoalsRoute
  '/onboarding/level': typeof AuthenticatedOnboardingLevelRoute
  '/onboarding/skills': typeof AuthenticatedOnboardingSkillsRoute
  '/skills/$skillId/pathway': typeof SkillsSkillIdPathwayRoute
  '/skills/$skillId/': typeof SkillsSkillIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/personal-training': typeof PersonalTrainingRoute
  '/signup': typeof SignupRoute
  '/subscription': typeof SubscriptionRoute
  '/welcome': typeof WelcomeRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skills': typeof SkillsIndexRoute
  '/lesson/$lessonId': typeof AuthenticatedLessonLessonIdRoute
  '/onboarding/goals': typeof AuthenticatedOnboardingGoalsRoute
  '/onboarding/level': typeof AuthenticatedOnboardingLevelRoute
  '/onboarding/skills': typeof AuthenticatedOnboardingSkillsRoute
  '/skills/$skillId/pathway': typeof SkillsSkillIdPathwayRoute
  '/skills/$skillId': typeof SkillsSkillIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/personal-training': typeof PersonalTrainingRoute
  '/signup': typeof SignupRoute
  '/subscription': typeof SubscriptionRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/skills/': typeof SkillsIndexRoute
  '/_authenticated/lesson/$lessonId': typeof AuthenticatedLessonLessonIdRoute
  '/_authenticated/onboarding/goals': typeof AuthenticatedOnboardingGoalsRoute
  '/_authenticated/onboarding/level': typeof AuthenticatedOnboardingLevelRoute
  '/_authenticated/onboarding/skills': typeof AuthenticatedOnboardingSkillsRoute
  '/skills/$skillId/pathway': typeof SkillsSkillIdPathwayRoute
  '/skills/$skillId/': typeof SkillsSkillIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/personal-training'
    | '/signup'
    | '/subscription'
    | '/welcome'
    | '/achievements'
    | '/admin'
    | '/home'
    | '/profile'
    | '/progress'
    | '/settings'
    | '/skills/'
    | '/lesson/$lessonId'
    | '/onboarding/goals'
    | '/onboarding/level'
    | '/onboarding/skills'
    | '/skills/$skillId/pathway'
    | '/skills/$skillId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/personal-training'
    | '/signup'
    | '/subscription'
    | '/welcome'
    | '/achievements'
    | '/admin'
    | '/home'
    | '/profile'
    | '/progress'
    | '/settings'
    | '/skills'
    | '/lesson/$lessonId'
    | '/onboarding/goals'
    | '/onboarding/level'
    | '/onboarding/skills'
    | '/skills/$skillId/pathway'
    | '/skills/$skillId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/personal-training'
    | '/signup'
    | '/subscription'
    | '/welcome'
    | '/_authenticated/achievements'
    | '/_authenticated/admin'
    | '/_authenticated/home'
    | '/_authenticated/profile'
    | '/_authenticated/progress'
    | '/_authenticated/settings'
    | '/skills/'
    | '/_authenticated/lesson/$lessonId'
    | '/_authenticated/onboarding/goals'
    | '/_authenticated/onboarding/level'
    | '/_authenticated/onboarding/skills'
    | '/skills/$skillId/pathway'
    | '/skills/$skillId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PersonalTrainingRoute: typeof PersonalTrainingRoute
  SignupRoute: typeof SignupRoute
  SubscriptionRoute: typeof SubscriptionRoute
  WelcomeRoute: typeof WelcomeRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  SkillsSkillIdPathwayRoute: typeof SkillsSkillIdPathwayRoute
  SkillsSkillIdIndexRoute: typeof SkillsSkillIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-training': {
      id: '/personal-training'
      path: '/personal-training'
      fullPath: '/personal-training'
      preLoaderRoute: typeof PersonalTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lesson/$lessonId': {
      id: '/_authenticated/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof AuthenticatedLessonLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/goals': {
      id: '/_authenticated/onboarding/goals'
      path: '/onboarding/goals'
      fullPath: '/onboarding/goals'
      preLoaderRoute: typeof AuthenticatedOnboardingGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/level': {
      id: '/_authenticated/onboarding/level'
      path: '/onboarding/level'
      fullPath: '/onboarding/level'
      preLoaderRoute: typeof AuthenticatedOnboardingLevelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/skills': {
      id: '/_authenticated/onboarding/skills'
      path: '/onboarding/skills'
      fullPath: '/onboarding/skills'
      preLoaderRoute: typeof AuthenticatedOnboardingSkillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/skills/$skillId/': {
      id: '/skills/$skillId/'
      path: '/skills/$skillId'
      fullPath: '/skills/$skillId/'
      preLoaderRoute: typeof SkillsSkillIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$skillId/pathway': {
      id: '/skills/$skillId/pathway'
      path: '/skills/$skillId/pathway'
      fullPath: '/skills/$skillId/pathway'
      preLoaderRoute: typeof SkillsSkillIdPathwayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedLessonLessonIdRoute: typeof AuthenticatedLessonLessonIdRoute
  AuthenticatedOnboardingGoalsRoute: typeof AuthenticatedOnboardingGoalsRoute
  AuthenticatedOnboardingLevelRoute: typeof AuthenticatedOnboardingLevelRoute
  AuthenticatedOnboardingSkillsRoute: typeof AuthenticatedOnboardingSkillsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedLessonLessonIdRoute: AuthenticatedLessonLessonIdRoute,
  AuthenticatedOnboardingGoalsRoute: AuthenticatedOnboardingGoalsRoute,
  AuthenticatedOnboardingLevelRoute: AuthenticatedOnboardingLevelRoute,
  AuthenticatedOnboardingSkillsRoute: AuthenticatedOnboardingSkillsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PersonalTrainingRoute: PersonalTrainingRoute,
  SignupRoute: SignupRoute,
  SubscriptionRoute: SubscriptionRoute,
  WelcomeRoute: WelcomeRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  SkillsSkillIdPathwayRoute: SkillsSkillIdPathwayRoute,
  SkillsSkillIdIndexRoute: SkillsSkillIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
